name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build_and_deploy_to_aeweb:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to AEweb
        id: deploy
        uses: archethic-foundation/aeweb-github-action@v1.6.3
        with:
          seed: ${{ secrets.ARCH_BASE_TESTNET_SEED }}
          endpoint: "https://testnet.archethic.net"
          path: "./build"
